# 011. PyTorch basic Crash

- GPU 필요하므로 Colab 에서 실행

In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

device = "cuda:0" if torch.cuda.is_available() else "cpu"
device

'cuda:0'

In [2]:
torch.__version__

'2.3.1+cu121'

## Tensor Data Types

<img src="https://miro.medium.com/max/875/1*-C10tKbZ2h0Zd7maau86oQ.png" height="400" />

### torch.tensor 함수

`tensor(data, dtype=None, device=None, requires_grad=False) -> Tensor`

     data (array_like): list, tuple, numpy ndarray, scalar, and other types.
     dtype :  `None`인 경우 `data`에서 데이터 유형을 유추합니다.  
     device : `cpu`, `cuda`  
     require_grad(bool, optional): autograd가 작업을 기록해야 하는 경우

Float torch tensor 생성

In [3]:
# numpy array 생성
a = np.ones((2, 3))
# tensor  생성
b = torch.tensor(a)
# dtype
print(a.dtype, '\t', b.dtype)

float64 	 torch.float64


In [4]:
# numpy 생성
a = np.ones((2, 3), dtype="float32")
# tensor 생성
b = torch.tensor(a)
# dtype
print(a.dtype, '\t', b.dtype)

float32 	 torch.float32


Integer tensor 생성

In [5]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int32)
x

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [6]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int32, device=device)
x

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0', dtype=torch.int32)

## 1D Tensor Operation

### tensor 생성

In [7]:
a = torch.tensor([1, 2, 3, 4, 5])

a[0], a[-1]

(tensor(1), tensor(5))

In [8]:
a.size()

torch.Size([5])

In [9]:
a.ndimension()

1

In [10]:
a.view(5, 1)

tensor([[1],
        [2],
        [3],
        [4],
        [5]])

In [11]:
# cpu tensor
a = torch.FloatTensor([0, 1, 2, 3, 4])
a

tensor([0., 1., 2., 3., 4.])

In [12]:
# gpu tensor
a = torch.cuda.FloatTensor([0, 1, 2, 3, 4])
a

<ipython-input-12-bcf1493b08d5>:2: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:78.)
  a = torch.cuda.FloatTensor([0, 1, 2, 3, 4])


tensor([0., 1., 2., 3., 4.], device='cuda:0')

### Tensor Type 변환

- cpu <--> gpu

In [13]:
# cpu tensor
a = a.type(torch.FloatTensor)
a

tensor([0., 1., 2., 3., 4.])

In [14]:
# gpu tensor
b = a.to(device)
b

tensor([0., 1., 2., 3., 4.], device='cuda:0')

In [15]:
b = a.cuda()
b

tensor([0., 1., 2., 3., 4.], device='cuda:0')

In [16]:
c = a.type(torch.cuda.FloatTensor)
c

tensor([0., 1., 2., 3., 4.], device='cuda:0')

In [17]:
# cpu tensor
d = b.to("cpu")
d

tensor([0., 1., 2., 3., 4.])

In [18]:
e = c.cpu()
e

tensor([0., 1., 2., 3., 4.])

### Tensor 생성

- 무작위로 초기화된 행렬 생성 (uniform distribution)

In [19]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4363, 0.7677, 0.0048],
        [0.0156, 0.2046, 0.1983],
        [0.4778, 0.4162, 0.5468],
        [0.9259, 0.8934, 0.2729],
        [0.5883, 0.5510, 0.0524]])


- dtype이 long이고 0으로 채워진 행렬 생성

In [20]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)
print(x.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.int64


- python list로 부터 tensor 생성

In [21]:
a = torch.tensor([7, 4, 3, 2, 6])
a.type(), a.dtype

('torch.LongTensor', torch.int64)

In [22]:
b = torch.FloatTensor([7, 4, 3, 2, 6])
b.type(), b.dtype

('torch.FloatTensor', torch.float32)

In [23]:
a == b

tensor([True, True, True, True, True])

torch.LongTensor --> torch.long, torch.int64

In [24]:
c = torch.tensor([7, 4, 3, 2, 6], dtype=torch.int64)
c

tensor([7, 4, 3, 2, 6])

In [25]:
d = torch.LongTensor([7, 4, 3, 2, 6])
d

tensor([7, 4, 3, 2, 6])

In [26]:
c == d

tensor([True, True, True, True, True])

## Tensor 의 shape & dimension (rank)

In [27]:
a = torch.Tensor([0, 1, 2, 3, 4])
a.size()

torch.Size([5])

In [28]:
# size() 와 shape 은 alias
a.shape

torch.Size([5])

In [29]:
a.ndimension()

1

## torch.view : original tensor의 memory 공유

In [30]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


## numpy 와 tensor 간의 호환성

- memory 를 공유하므로 하나를 수정하면 나머지에 모두 반영  

In [31]:
numpy_array = np.array([0.0, 1.0, 2.0, 3.0, 4.0, 5.0])       # numpy array
torch_tensor = torch.from_numpy(numpy_array)               # torch tensor
torch_tensor

tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64)

In [32]:
back_to_numpy = torch_tensor.numpy()           # numpy array
back_to_numpy

array([0., 1., 2., 3., 4., 5.])

In [33]:
numpy_array, torch_tensor, back_to_numpy

(array([0., 1., 2., 3., 4., 5.]),
 tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64),
 array([0., 1., 2., 3., 4., 5.]))

In [34]:
back_to_numpy[0] = 100

numpy_array, torch_tensor, back_to_numpy

(array([100.,   1.,   2.,   3.,   4.,   5.]),
 tensor([100.,   1.,   2.,   3.,   4.,   5.], dtype=torch.float64),
 array([100.,   1.,   2.,   3.,   4.,   5.]))

## Scalar value

- 만약 tensor에 하나의 값만 존재한다면, ``.item()`` method를 사용하여 숫자 값을 얻을 수 있습니다.  

In [35]:
x = torch.randn(1)
x.item()

-0.7823981046676636

In [36]:
a = torch.tensor([5., 3., 4., 1.])

print(a[0])
print(a[0].item())

tensor(5.)
5.0


- tensor 가 array 형태인 경우 `numpy()` method 를 통해 ndarray 반환

In [37]:
x = torch.randn(2)
print(x)
print()
print(x.numpy())

tensor([-1.7493,  0.7970])

[-1.7492791  0.7970435]


### torch.sum, torch.max, torch.min, torch.argmax, torch.argmin

- torch.sum(input, dim, keepdim=False, dtype=None) → Tensor  
주어진 차원 dim에서 입력 텐서의 각 행의 합(max, min)을 반환합니다.

- dim 을 지정한 경우, 지정된 dim을 축소하는 것입니다. 따라서 dim 0(행)을 접으면 하나의 행이 됩니다(열 단위로 합산).

In [38]:
x = torch.tensor([
     [1, 2, 3],
     [4, 5, 6]
   ])
x.shape

torch.Size([2, 3])

In [39]:
torch.max(x, axis=0), torch.min(x, axis=0)

(torch.return_types.max(
 values=tensor([4, 5, 6]),
 indices=tensor([1, 1, 1])),
 torch.return_types.min(
 values=tensor([1, 2, 3]),
 indices=tensor([0, 0, 0])))

In [40]:
torch.max(x, axis=1), torch.min(x, axis=1)

(torch.return_types.max(
 values=tensor([3, 6]),
 indices=tensor([2, 2])),
 torch.return_types.min(
 values=tensor([1, 4]),
 indices=tensor([0, 0])))

In [41]:
torch.argmax(x), torch.argmin(x)

(tensor(5), tensor(0))

In [42]:
torch.argmax(x, axis=0), torch.argmin(x, axis=0)

(tensor([1, 1, 1]), tensor([0, 0, 0]))

In [43]:
torch.argmax(x, axis=1), torch.argmin(x, axis=1)

(tensor([2, 2]), tensor([0, 0]))

# Backpropagation 과 경사하강법 적용

- weight 와 bias를 스스로 학습
- (습도, 강수량, 최고온도, 최저온도)를 feature 로 입력 받아  (사과, 오렌지)의 수확량(label)을 선형회귀로 예측하는 model 작성

In [44]:
# Input (습도, 강수량, 최고온도, 최저온도)
inputs = np.array([
                   [73, 67, 43, 10],
                   [91, 88, 64, 5],
                   [87, 134, 58, 2],
                   [102, 43, 37, 4],
                   [69, 96, 70, 5]], dtype='float32')

# Targets - (apples, oranges) 수확량
targets = np.array([
                    [56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

- input 과 target을 tensor로 변환

In [45]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs.size())
print(targets.size())

torch.Size([5, 4])
torch.Size([5, 2])


In [46]:
from torch import nn
from torch.nn import Linear
from torch import optim

torch.manual_seed(1)

In [47]:
# 입력 특징의 크기가 4이고 출력 특징의 크기가 2인 선형 모델을 정의합니다.
model = nn.Linear(in_features=4, out_features=2)

In [48]:
# 손실 함수로 평균 제곱 오차(MSE)를 정의합니다.
criterion = nn.MSELoss()

# 모델의 매개변수를 최적화하기 위해 확률적 경사 하강법(SGD) 옵티마이저를 정의합니다.
# 학습률(lr)은 1e-4로 설정합니다.
optimizer = optim.SGD(model.parameters(), lr=1e-4)

In [49]:
for epoch in range(100):               # 총 100번의 에포크 동안 학습을 반복합니다.
    for x, y in zip(inputs, targets):  # 입력 데이터와 타겟 데이터를 쌍으로 묶어 순회합니다.
        yhat = model(x)                # 모델에 입력 x를 전달하여 예측값 yhat을 얻습니다.
        loss = criterion(yhat, y)      # 예측값 yhat과 실제값 y를 비교하여 손실(loss)을 계산합니다.
        loss.backward()                # 손실에 대한 그래디언트를 계산합니다.
        optimizer.step()               # 옵티마이저를 사용하여 모델의 가중치를 업데이트합니다.
        optimizer.zero_grad()          # 다음 반복을 위해 옵티마이저의 그래디언트를 초기화합니다.

In [50]:
# 모델에 전체 입력 데이터를 전달하여 예측값(preds)을 얻습니다.
preds = model(inputs)

# 예측값(preds)과 실제 타겟값(targets)을 비교하여 손실(loss)을 계산합니다.
loss = criterion(preds, targets)
print(loss)

tensor(4.0759, grad_fn=<MseLossBackward0>)


In [51]:
# Predictions & target 비교
print(targets.detach().numpy())
print()
print(preds.detach().numpy())

[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]

[[ 58.021603  69.747055]
 [ 83.15652   98.78548 ]
 [119.96505  128.44089 ]
 [ 21.839664  34.988003]
 [102.80343  117.893585]]
